[target.aarch64-apple-darwin]
runner = "native" # Use the native macOS build toolchain (requires macOS runner)

[target.x86_64-apple-darwin]
runner = "native" # Use the native macOS build toolchain (requires macOS runner)

[target.x86_64-pc-windows-msvc]
runner = "native" # Use the native Windows build toolchain (requires Windows runner)
