project:
  type: website

website:
  navbar:
    logo: images/logo.png
    background: primary
    right:
      - text: "Home"
        href: index.qmd
      - text: "Getting Started"
        href: getting-started.qmd
      - text: "From"
        href: from.qmd
      - text: "To"
        href: to.qmd
      - text: "Transformers"
        href: transformers.qmd
      - text: "Roadmap"
        href: roadmap.qmd

  sidebar:
    style: docked  # Enables the Table of Contents sidebar
    search: true  # Enables the search bar
    contents:
      - index.qmd
      - getting-started.qmd
      - from.qmd
      - to.qmd
      - transformers.qmd
      - roadmap.qmd

theme:
  light: sandstone
  dark: darkly

format:
  html:
    css: styles.css