name: Publish Quarto Docs

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Quarto Setup
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Quarto Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          path: docs           # <--- key fix here
          target: gh-pages     # or whichever branch you want
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
