name: Publish Quarto Website

on:
  push:
    branches:
      - main  # or whichever branch you use

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repository code
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Set up Quarto on the runner
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # 3. Render and publish the Quarto project from "docs" to "gh-pages"
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          render: docs      # location of your Quarto project folder
          to: gh-pages      # branch for Pages
