name: Release Pipeline

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build Artifacts
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
        target:
          ubuntu-latest: [x86_64-unknown-linux-gnu]
          macos-latest: [aarch64-apple-darwin, x86_64-apple-darwin]
          windows-latest: [x86_64-pc-windows-msvc]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install cross
        if: ${{ matrix.runner == 'ubuntu-latest' }}
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build Binary
        run: |
          if [ "${{ matrix.runner }}" == "ubuntu-latest" ]; then
            cross build --release --target ${{ matrix.target }}
          else
            cargo build --release --target ${{ matrix.target }}
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-binary
          path: target/${{ matrix.target }}/release
          retention-days: 7

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Release v${{ github.ref_name }}"
          body: |
            ### Changes
            - Automatically built binaries are attached below.
          files: |
            artifacts/x86_64-unknown-linux-gnu/*
            artifacts/x86_64-pc-windows-msvc/*
            artifacts/aarch64-apple-darwin/*
            artifacts/x86_64-apple-darwin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
