name: Release Pipeline

on:
  push:
    tags:
      - 'v*'        # e.g., v0.1.0
  workflow_dispatch: # allow manual runs

jobs:
  build:
    name: Build Artifacts
    strategy:
      matrix:
        include:
          # Build on Ubuntu with cross
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          # macOS Intel
          - os: macos-latest
            target: x86_64-apple-darwin

          # macOS Apple Silicon
          - os: macos-latest
            target: aarch64-apple-darwin

          # Windows
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Rust (stable)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Add Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Install cross (Ubuntu only)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build binary
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            cross build --release --target ${{ matrix.target }}
          else
            cargo build --release --target ${{ matrix.target }}
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-binary
          path: target/${{ matrix.target }}/release
          retention-days: 7

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Release v${{ github.ref_name }}"
          body: |
            ### Changes
            - Automatically built binaries attached below.
          files: |
            artifacts/x86_64-unknown-linux-gnu/*
            artifacts/aarch64-apple-darwin/*
            artifacts/x86_64-apple-darwin/*
            artifacts/x86_64-pc-windows-msvc/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
